// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-1U5ArNfxMHbNJqinKaOdwirkK883Cco',
    appId: '1:546064424992:web:db806a8056f5d3ea32dc45',
    messagingSenderId: '546064424992',
    projectId: 'et3am-ca94c',
    authDomain: 'et3am-ca94c.firebaseapp.com',
    storageBucket: 'et3am-ca94c.firebasestorage.app',
    measurementId: 'G-LZ8XCKMW74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEhUrWxVfya0hQE5XzTiVgsdnIINfrhLs',
    appId: '1:546064424992:android:bff11ecd74a1a1e832dc45',
    messagingSenderId: '546064424992',
    projectId: 'et3am-ca94c',
    storageBucket: 'et3am-ca94c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFvT5QSTN5BqliE4jd_3tHQNiKATd_0vA',
    appId: '1:546064424992:ios:d771da6ebe017fc532dc45',
    messagingSenderId: '546064424992',
    projectId: 'et3am-ca94c',
    storageBucket: 'et3am-ca94c.firebasestorage.app',
    iosBundleId: 'com.et3amappios.eqmsapp',
  );
}
